interface Friend {
  avatar: string; // 头像链接
  name: string; // 用户 id
  link: string; // 博客链接
  title?: string; // 用户头衔
  tag?: string; // 用户标签
  color?: string; // 标签颜色
}

/**
 * TODO: 缺项处理
 * 在此处填写你的友情链接
 */
export const friendsInfo: Friend[] = [
  {
    avatar: "https://avatars.githubusercontent.com/u/49082837?v=4",
    name: "ZbWeR",
    title: "Blog模板作者 🪁",
    link: "https://blog.zbwer.work/",
    tag: "电子科技大学👨‍🎓",
    color: "indigo",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/116318567?v=4",
    name: "Sherlock 霍尔木兹海峡长",
    title: "🚀 一个幸运的人",
    link: "https://holdme.fun/",
    tag: "哈尔滨工业大学（威海）",
    color: "indigo",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/118501068?v=4",
    name: "阿普瑞斯   Apries",
    title: "所向云野 🪁",
    link: "https://github.com/Apries406",
    tag: "西南石油大学",
    color: "pink",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/151838381?v=4",
    name: "Wu Yutong",
    title: "CuSO4wyt",
    link: "https://github.com/CuSO4wyt",
    tag: "27' Computer Science 南京大学",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/66943144?v=4",
    name: "Youyi Huang  YYForReal",
    title: "擅长前端，了解后端，语言模型。爱好强化学习🌟",
    link: "https://github.com/YYForReal",
    tag: "深圳大学本硕",
    color: "green",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/96616876?v=4",
    name: "小李不在_",
    title: " 👨🏾‍🦱 xiaolibuzai-ovo 🥵",
    link: "https://github.com/xiaolibuzai-ovo",
    tag: "A back-end development engineer",
    color: "orange",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/109739893?v=4",
    name: "轩哥 Rainyrou BenXuan",
    title: "华南农业大学酸奶好好喝😋",
    link: "https://github.com/Rainyrou",
    tag: "华南农业大学 PatSnap -> XiaoMi",
    color: "indigo",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/96854855?v=4",
    name: "Winches",
    title: "NextUI 核心成员，开源爱好者 🎃",
    link: "https://awesome-15docs.netlify.app/",
    tag: "广东海洋大学 打渔为生 🐟",
    color: "indigo",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/65701285?v=4",
    name: "Lujie Ma ",
    title: "🥳XiaoLinZzz 👨‍💻",
    link: "https://github.com/XiaoLinZzz",
    tag: "University of Melbourne",
    color: "pink",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/28774128?v=4",
    name: "Alexlin625",
    title: "Alexlin625",
    link: "https://github.com/Alexlin625",
    tag: "华南理工大学",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/95062803?v=4",
    name: "gronk",
    title: "狗叫 🐶 jianyi-gronk 🥵",
    link: "https://github.com/jianyi-gronk",
    tag: "江西财经大学",
    color: "green",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/122708836?v=4",
    name: "Lay",
    title: "努力努力再努力！！！✨",
    link: "https://github.com/NJUPTlay",
    tag: "南京邮电大学",
    color: "orange",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/122970069?v=4",
    name: "Fanceir Fan Xu",
    title:
      "I'm a Computer Science and Technology student passionate about frontend development, currently diving deep into learning React.！✨",
    link: "https://github.com/Fanceir",
    tag: "江南大学",
    color: "orange",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/63275695?v=4",
    name: "pepedd864",
    title: "pepedd864",
    link: "https://github.com/pepedd864",
    tag: "江西财经大学",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/118599811?v=4",
    name: "ha9",
    title: "✨",
    link: "https://github.com/Khaoden",
    tag: "江苏科技大学",
    color: "white",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/46275354?v=4",
    name: "苏向夜",
    title: "The information was blocked👻",
    link: "https://github.com/fu050409",
    tag: "Southwest Petroleum University",
    color: "sky",
  },
  {
    avatar:
      "https://avatars.githubusercontent.com/u/52227746?s=400&u=785c2e323003c6873019faa692c935d55ae8aec0&v=4",
    name: "大专哥",
    title: "I hope everyone's dreams come true",
    link: "https://sk-luffa.github.io/note_docs/",
    tag: "大专",
    color: "magenta",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/113702528?v=4",
    name: "ice_dk",
    title: "🎈我们都会成为很棒的小孩!",
    link: "https://github.com/CCCdk",
    tag: "广东金融学院",
    color: "green",
  },
  {
    avatar: "https://nohup.life/image/avator.jpg",
    name: "nohup",
    title: "我是一阵自由的风。",
    link: "https://nohup.life/",
    tag: "我是一阵自由的风。",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/31147639?v=4",
    name: "dc392",
    title: "pursue truth🫠",
    link: "https://personal-blog-fzfb.onrender.com/",
    tag: "武汉大学",
    color: "orange",
  },
  {
    avatar:
      "https://blog.xianfei.win/imgs/avatar2_hu71215836cfc1201dad43a2a602d405c9_1044873_300x0_resize_box_3.png",
    name: "xianfei",
    title: "欢迎访问Xianfei的博客！",
    link: "https://blog.xianfei.win/",
    tag: "HKUST",
    color: "sky",
  },
  {
    avatar: "https://assets.hikarilan.life/avatar.png",
    name: "HikariLan",
    title: "兰草凋荡，星辰璀璨",
    link: "https://my.minecraft.kim",
    tag: "西安财经大学",
    color: "orange",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/127511305?v=4",
    name: "HeMingguo",
    title: "TO BE, WILL BE",
    link: "https://github.com/hemingguo",
    tag: "南京大学",
    color: "orange",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/36628162?v=4",
    name: "Tony",
    title: "Whatever it takes.😎",
    link: "https://github.com/cheeseburgertony",
    tag: "A front-end developer",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/153916948?v=4",
    name: "BirdyLu",
    title: "Always aim to surpass the reality",
    link: "https://github.com/BirdyLu",
    tag: "Learning front-end",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/144657059?v=4",
    name: "WhythZ",
    title: "华南理工大学",
    link: "https://whythz.github.io",
    tag: "喜欢游戏和游开",
    color: "pink",
  },
    {
    avatar: "https://k0001y.com/.blog/img/bird.png",
    name: "K0001y",
    title: "time to cast",
    link: "https://k0001y.com/.blog/index.html",
    tag: "DLUT,大雪深埋",
    color: "sky",
  },
  {
    avatar: "https://avatars.githubusercontent.com/u/169412732?s=400&u=933febfca67855e05fb5cd91e5784c6d7cede2ed&v=4",
    name: "RenaYin",
    title: "自由灵魂✨",
    link: "https://github.com/Rena-Yin",
    tag: "华盛顿大学",
    color: "azure",
  },
];
